language: java
jdk: oraclejdk8
sudo: required
services:
  - docker
env:
  - buildCMD="p2-brocker && gradle build"
  - buildCMD="p2-query-service && mvn clean verify -B -f pom.xml"
script: cd $buildCMD
