language: java
jdk: oraclejdk8
sudo: required
services:
  - docker
script: mvn clean verify -B -f pom.xml
deploy:
  provider: heroku
  api_key:
    secure: YvJjbLXnVR/scKFAP5+QiwYZZmh8iJ47QaSkIePsY2Q3QDI3IPhClaAvDyb4wT6BhQmbYgj5Yc830MrKzsuUN842+2WZGtkxzUeJtz3Lwj6bKW4u5AX3IHN5Na5siRcDr/zDnRG0g4dNATWwgebxatsOSCBeplf+63X2J8+EBijwL5Y+4plDGPAzJNPcHxtMEuQYFmtlBYG6iQvXsv+Mj/bqYAnGsvhoLC5MuWEQ3DKFMor2GpFQFFDDLlM9mLbIP+8sX/VN7vBNOzg9KiHS4/X+cDH+YQZDJ3bDLTrstsEsR3z1oR3jQ3nPNmkidxcefa/HLWsdwxFsMsAxjeCmT3pZCqrlLhGkWTIvvZECb3eBEaLUSy1hYGKFsGsY065T658rm5OltXy8PIf2Uhcie4G5i2BWVwolodO9I/LdYcLeBZiJk0wzfCYTHNK/Wi/UCR4eUMmJ+kR9DGmfKtK5B5mbkFNXzvhQ8KQfrc1aWDiTVNs4gmcRzPyRNbnMCARKgv9kybbRhcK1/gmw8Grzs/4DRiQ/ZCS0pG58AnGUGJBIlQ7tELeWuv8+bN3x9DtLi9GEn8vUmTyo+rlz7trhGpsSkUtIsqLhwQPBG1PCEyTHoxK9BfPTuepNJhRTNr6RNsGTxffD/kXoxcKVB2Bk2Qbrh8456XL549V/PazOpQU=
  app: p2-query-service
